# Site settings
name: Jithendra Yenugula
title: Jithendra Yenugula | Data Engineer
description: Software engineer focused on building scalable data systems and solutions
url: https://jithendray.github.io/
baseurl: ''
email: jithendra.yenugula@gmail.com
cover: https://jithendray.github.io/img/og.png
logo: https://jithendray.github.io/img/emojis/rocket.png
resume: https://bit.ly/jithendray-resume
social:
  - title: email
    url: mailto:jithendra.yenugula@gmail.com
  - title: github
    url: https://github.com/jithendray
  - title: linkedin
    url: https://www.linkedin.com/in/jithendray
  - title: twitter
    url: https://twitter.com/doomedripper
  

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
